version: "3"
services:
  backend:
    build:
      context: ../       # Goes up one level to 'fstapi/' for backend Dockerfile
    container_name: backend
    ports:
      - "8080:8000"

  frontend:
    build:
      context: .         # Stay in 'front_end/' for frontend Dockerfile
    container_name: react-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
